### PR TITLE
Feature/routes override

### PR DESCRIPTION
**Pull request by pralhadstha**
Added an ability to override the `routes` of all `modules`.

### CODE REVIEW

**Comment by nWidart** [comment]
Hi,

Thanks for your contribution but I don't see a need in this. This can already be done by loading those routes in the App/Providers/RouteServiceProvider class.

**Comment by pralhadstha** [comment]
Hi @nWidart , 

Yes the `routes` are loaded in `App/Providers/RouteServiceProvide` but it loads the `routes.php` after all the `Modules` routes are loaded, which doesn't allow us to override the existing routes. 
While using the code below allows us to load the `routes.php` at the begining allowing us to only override some routes that are necessary to be overridden and keeping all other routes as it is.

```
          $this->app->booted(function () {
                include __DIR__ . '/../../../app/Http/routes.php';
           });
```

Note: Also in `Laravel 5.3` the `routes folder` is shifted out of `app` directory. I will update the code for newer versions.

**Comment by nWidart** [comment]
Oh ok, that's strange since the RouteSP is loaded before the AsgardSP. https://github.com/AsgardCms/Platform/blob/2.0/config/app.php#L178

It would be nice to find out why, since otherwise this would force users to place the routes where you define it. Or, worst case, make it configurable.

**Comment by pralhadstha** [comment]
@nWidart 
Yeah that's strange. As i am also surprised to see `AsgardServiceProvider's route` being loaded first than `RouteServiceProvider's route`. I am not sure what is creating the issue. Will notify when i get to find the main cause or any other solutions.

**Comment by pralhadstha** [comment]
@nWidart Closing this pull request as i have found another way that doesn't touches all other modules.

**Pull request closed without merging**
